version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_DB: db_example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
